
server.port=8080

# Swagger / OpenAPI
springdoc.swagger-ui.enabled=true
springdoc.api-docs.enabled=true

# Logging
#logging.level.root=INFO
#logging.level.com.homesteader2=INFO
#logging.file.name=logs/homesteader2.log

# PostgreSQL Database
spring.datasource.url=jdbc:postgresql://localhost:5432/homesteader2
spring.datasource.username=postgres
spring.datasource.password=7756990677@sumit
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# File Upload
spring.servlet.multipart.max-file-size=500MB
spring.servlet.multipart.max-request-size=500MB

# JSP
spring.mvc.view.prefix=/pages/
spring.mvc.view.suffix=.jsp