spring.mvc.view.prefix=/pages/
spring.mvc.view.suffix=.jsp

server.port = 8081

springdoc.swagger-ui.enabled=true
springdoc.api-docs.enabled=true

weather.api.key=1fbd5b6dc0a3b21b5991097c82147f1d


 Root logging level
logging.level.root=INFO

# Custom package logging
logging.level.com.homesteaderindia=INFO

# Log file output
logging.file.name=logs/homesteader.log
logging.file.path=logs


spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/homesteaderFinal
spring.datasource.username=postgres
spring.datasource.password=7756990677@sumit
spring.jpa.hibernate.ddl-auto=update


# Set the maximum allowed file size (in bytes)
spring.servlet.multipart.max-file-size=500MB
# Set the maximum allowed request size (in bytes)
spring.servlet.multipart.max-request-size=500MB

